name: copts
version: '0.0.1'
category: Console
author: Fernando Oliveira
copyright: 2017 Wando-HS
license: MIT
github: wando-hs/copts

default-extensions:
  - OverloadedStrings
  - EmptyCase
  - FlexibleContexts
  - FlexibleInstances
  - InstanceSigs
  - MultiParamTypeClasses
  - LambdaCase
  - MultiWayIf
  - NamedFieldPuns
  - TupleSections
  - ScopedTypeVariables
  - TypeApplications

dependencies:
  - base
  - containers
  - megaparsec
library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -Werror
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -fno-warn-missing-signatures
    - -Wmissing-exported-signatures
    - -threaded
    - -O2
    - -rtsopts
    - -with-rtsopts=-N
executables:
  copts:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -Wall
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wredundant-constraints
      - -fno-warn-missing-signatures
      - -Wmissing-exported-signatures
      - -threaded
      - -O2
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - copts
      - pretty-show
tests:
  copts-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - copts
    - hspec
    - hspec-megaparsec
